name: Flutter Build & Generate APK Artifact

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Auto-Heal & Create Android Structure
        run: |
          PROJECT_NAME=$(grep '^name:' pubspec.yaml | head -n 1 | awk '{print $2}' | tr -d '\r' | tr -d '"' | tr -d "'")
          rm -rf android ios .dart_tool build
          flutter create . --project-name "$PROJECT_NAME" --platforms=android

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
